### ISSUE TITLE
error: use of undeclared identifier 'XCreateWindow'

### ISSUE THREAD

**Issue by frchalaoux** [micmacIGN/micmac#102] opened 2018-09-14 10:28 UTC
Hi All,

I trying to compile MicMac with the Latest MASTER commit dd34f2f  9 days ago and I got these errors.
My OS system is Mac Sierra, X11 and all dependancies seems well installed.

in the fen_x11.cpp I can read :

   Window  w;
   XEvent glob_event;

  XSetWindowAttributes attr;

  attr.colormap =  ded->_cmap;
  attr.background_pixel = 0;
  int val_mask = CWColormap | CWBackPixel;

  w = XCreateWindow
  (
           ded->_disp,
           mother,
           p0.x,p0.y,
           sz.x,sz.y,
           border_witdh, 
           ded->_xvi.depth,
           InputOutput,
           ded->_xvi.visual,
           val_mask,
           &attr
  );

------------------

Questions:

What "use of undeclared identifier 'XMapWindow" error (see below) means in this context ?
Forgetting to include the header file that contains the function declaration ? My X11 (XQuartz 2.7.11) is coming from https://www.xquartz.org.

Is there a solution to compile MicMac in a first step without X11, what are the CMake directives in CMakeLists.txt file or on the command line to disable ? 

Is there anybody capable to help me in this compilation ?

UPDATE: But It seems to compile with the beta13 version, what is the relevent diff ?

FR

-----------------

Eros:MicMacOS_v5368 frchalaoux$ cd /Applications/MicMac/micmac/build
Eros:build frchalaoux$ /Applications/CMake.app/Contents/bin/cmake -DWITH_QT5=1 -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.11.1/ ../
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /System/Library/Frameworks/OpenGL.framework   
-- -----> OpenGL found
-- -----> using Qt 5.11.1
-- -----> Compile with c++11 support
-- -- FLAG:  -std=gnu++11
-- -- Git executable found
-- Derniere revision git de MicMac : v1.0.beta13-268-gdd34f2fc0
-- Configuring done
-- Generating done
-- Build files have been written to: /Applications/MicMac/micmac/build

---------------------
Eros:build frchalaoux$ make install -j4

[ 92%] Building CXX object src/CMakeFiles/elise.dir/xinterf/fen_x11.cpp.o
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:411:7: error: use of undeclared identifier 'XCreateWindow'
  w = XCreateWindow
      ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:426:3: error: use of undeclared identifier 'XMapWindow'
  XMapWindow(ded->_disp,w);
  ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:427:3: error: use of undeclared identifier 'XSelectInput'
  XSelectInput
  ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:439:6: error: use of undeclared identifier 'XWindowEvent'
     XWindowEvent(ded->_disp,w,ExposureMask,&glob_event);
     ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:440:6: error: use of undeclared identifier 'XMoveWindow'
     XMoveWindow(ded->_disp,w,p0.x,p0.y);
     ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:441:6: error: use of undeclared identifier 'XMapWindow'
     XMapWindow(ded->_disp,w);
     ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:448:7: error: use of undeclared identifier 'XChangeWindowAttributes'
      XChangeWindowAttributes(ded->_disp,w,CWBackingStore,&att);
      ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:477:5: error: use of undeclared identifier 'XRaiseWindow'
    XRaiseWindow(_devd->_disp,_w);
    ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:482:5: error: use of undeclared identifier 'XLowerWindow'
    XLowerWindow(_devd->_disp,_w);
    ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:489:5: error: use of undeclared identifier 'XMoveWindow'
    XMoveWindow(_devd->_disp,_w,aP.x,aP.y);
    ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:490:5: error: use of undeclared identifier 'XMapWindow'
    XMapWindow(_devd->_disp,_w);
    ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:521:23: error: use of undeclared identifier 'XDefaultRootWindow'
                /*_w*/XDefaultRootWindow(_devd->_disp),
                      ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:897:7: error: use of undeclared identifier 'XPutImage'
      XPutImage
      ^
1 warning generated.
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:1028:2: error: use of undeclared identifier 'XCopyArea'
        XCopyArea
        ^
[ 92%] Building CXX object src/CMakeFiles/elise.dir/xinterf/gen_win.cpp.o
In file included from /Applications/MicMac/micmac/src/xinterf/fen_graph_window.cpp:1:
In file included from /Applications/MicMac/micmac/include/StdAfx.h:148:
/Applications/MicMac/micmac/include/im_tpl/image.h:477:46: warning: instantiation of variable 'Tabul_Bits<1, true>::input_tab' required here, but no
      definition is available [-Wundefined-var-template]
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
/Applications/MicMac/micmac/include/im_tpl/image.h:483:27: note: in instantiation of member function 'TIm2DBits<1>::getOK' requested here
                          getOK(p)       :
                          ^
/Applications/MicMac/micmac/include/private/cElNuage3DMaille.h:210:30: note: in instantiation of member function 'TIm2DBits<1>::get' requested here
             return (mTImDef.get(anI,0) != 0);
                             ^
/Applications/MicMac/micmac/include/private/bitm_bits.h:103:34: note: forward declaration of template entity is here
        static  tLineInputTab *  input_tab;
                                 ^
/Applications/MicMac/micmac/include/im_tpl/image.h:477:46: note: add an explicit instantiation declaration to suppress this warning if
      'Tabul_Bits<1, true>::input_tab' is explicitly instantiated in another translation unit
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:1113:11: error: use of undeclared identifier 'XResizeWindow'
          XResizeWindow(_devd->_disp,_mother,_SzMere->x,_SzMere->y);
          ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:1114:11: error: use of undeclared identifier 'XMapWindow'
          XMapWindow(_devd->_disp,_mother);
          ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:1125:16: error: use of undeclared identifier 'XCreateWindow'
          _w = XCreateWindow
               ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:1138:11: error: use of undeclared identifier 'XMapWindow'
          XMapWindow(_devd->_disp,_w);
          ^
/Applications/MicMac/micmac/src/xinterf/fen_x11.cpp:1141:11: error: use of undeclared identifier 'XSelectInput'
          XSelectInput
          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
In file included from /Applications/MicMac/micmac/src/xinterf/fen_windows.cpp:1:
In file included from /Applications/MicMac/micmac/include/StdAfx.h:148:
/Applications/MicMac/micmac/include/im_tpl/image.h:477:46: warning: instantiation of variable 'Tabul_Bits<1, true>::input_tab' required here, but no
      definition is available [-Wundefined-var-template]
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
/Applications/MicMac/micmac/include/im_tpl/image.h:483:27: note: in instantiation of member function 'TIm2DBits<1>::getOK' requested here
                          getOK(p)       :
                          ^
/Applications/MicMac/micmac/include/private/cElNuage3DMaille.h:210:30: note: in instantiation of member function 'TIm2DBits<1>::get' requested here
             return (mTImDef.get(anI,0) != 0);
                             ^
/Applications/MicMac/micmac/include/private/bitm_bits.h:103:34: note: forward declaration of template entity is here
        static  tLineInputTab *  input_tab;
                                 ^
/Applications/MicMac/micmac/include/im_tpl/image.h:477:46: note: add an explicit instantiation declaration to suppress this warning if
      'Tabul_Bits<1, true>::input_tab' is explicitly instantiated in another translation unit
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
20 errors generated.
make[2]: *** [src/CMakeFiles/elise.dir/xinterf/fen_x11.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 warning generated.
1 warning generated.
In file included from /Applications/MicMac/micmac/src/xinterf/gen_win.cpp:1:
In file included from /Applications/MicMac/micmac/include/StdAfx.h:148:
/Applications/MicMac/micmac/include/im_tpl/image.h:477:46: warning: instantiation of variable 'Tabul_Bits<1, true>::input_tab' required here, but no
      definition is available [-Wundefined-var-template]
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
/Applications/MicMac/micmac/include/im_tpl/image.h:483:27: note: in instantiation of member function 'TIm2DBits<1>::getOK' requested here
                          getOK(p)       :
                          ^
/Applications/MicMac/micmac/include/private/cElNuage3DMaille.h:210:30: note: in instantiation of member function 'TIm2DBits<1>::get' requested here
             return (mTImDef.get(anI,0) != 0);
                             ^
/Applications/MicMac/micmac/include/private/bitm_bits.h:103:34: note: forward declaration of template entity is here
        static  tLineInputTab *  input_tab;
                                 ^
/Applications/MicMac/micmac/include/im_tpl/image.h:477:46: note: add an explicit instantiation declaration to suppress this warning if
      'Tabul_Bits<1, true>::input_tab' is explicitly instantiated in another translation unit
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
1 warning generated.
make[1]: *** [src/CMakeFiles/elise.dir/all] Error 2
make: *** [all] Error 2

**Comment by rjanvier** [comment] 2019-03-05 22:11
duplicate of #41 / double de #41

**Closed by rjanvier** 2019-03-05 22:11 UTC
Labels: duplicate, macos
